name: Deploy Serverless Snacks CDK Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Set up Node.js (required for CDK CLI)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install AWS CDK CLI
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Run tests
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/

      # Synthesize CDK stack
      - name: Synthesize CDK stack
        run: |
          source .venv/bin/activate
          cdk synth

      # Deploy CDK stack
      - name: Deploy CDK stack
        run: |
          source .venv/bin/activate
          cdk deploy --require-approval never --all
